# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title : Materia&trade;
tagline: Educational Games and Apps Platform
author :
  name : Learning Systems & Technologies, UCF
  email : techrangers@ucf.edu

baseurl: "/Materia-Docs"
url: "https://ucfopen.github.io" # the base hostname & protocol for your site, e.g. http://example.com

google_analytics_id : 'UA-16482230-3'

collections:
  # Version 10 collections
  v10_administrators:
    output: true
    permalink: /v10/admin/:name.html
  v10_authors:
    output: true
    permalink: /v10/create/:name.html
  v10_players:
    output: true
    permalink: /v10/play/:name.html
  v10_developers:
    output: true
    permalink: /v10/develop/:name.html
  v10_support:
    output: true
    permalink: /v10/support/:name.html
  # Version 11 collections
  v11_administrators:
    output: true
    permalink: /v11/admin/:name.html
  v11_users:
    output: true
    permalink: /v11/users/:name.html
  v11_developers:
    output: true
    permalink: /v11/develop/:name.html
  v11_support:
    output: true
    permalink: /v11/support/:name.html
  # Data-only collection
  users:
    output: false

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
      highlighter: yes

exclude:
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - vendor
